import type { PracticeArea, Insight } from './api';

// Local fallback data — used when the live API/database is unreachable,
// so the site never shows empty/error states. The two new priority
// services (foreigners' marriage documentation & residency permits)
// are placed first (sort_order 1 & 2), pushing the original 8 down.
export const localPracticeAreas: PracticeArea[] = [
  {
    id: 9,
    slug: 'foreigners-marriage',
    icon: 'users',
    title_ar: 'توثيق زواج الأجانب',
    title_en: "Foreigners' Marriage Documentation",
    summary_ar: 'توثيق عقود زواج الأجانب في مصر بسرعة وسرّية، والتصديق عليها لدى الجهات الرسمية والسفارات.',
    summary_en: "Documenting foreigners' marriage contracts in Egypt swiftly and confidentially, with certification before official authorities and embassies.",
    details_ar: 'نتولى كافة إجراءات توثيق زواج الأجانب من مصريين أو من جنسيات أخرى أمام الشهر العقاري والجهات المختصة، بما يشمل استخراج الأوراق المطلوبة، والترجمة المعتمدة، والتصديق القنصلي والتوثيق لدى السفارات، مع متابعة الإجراءات حتى استلام العقد موثقًا.',
    details_en: "We handle the full process of documenting foreigners' marriages to Egyptians or other nationalities before the notary and competent authorities — including preparing required documents, certified translation, consular authentication and embassy legalisation — following through until the contract is fully notarised.",
    sort_order: 1,
  },
  {
    id: 10,
    slug: 'residency-permits',
    icon: 'landmark',
    title_ar: 'التعامل مع الإقامات',
    title_en: 'Residency Permits',
    summary_ar: 'استخراج وتجديد إقامات الأجانب في مصر ومتابعة إجراءاتها أمام مصلحة الجوازات والهجرة.',
    summary_en: "Obtaining and renewing foreigners' residency permits in Egypt and handling procedures before the Passports & Immigration Authority.",
    details_ar: 'نساعد الأجانب المقيمين في مصر على استخراج وتجديد تصاريح الإقامة بأنواعها (العمل، الدراسة، الزواج من مصري/ة، الاستثمار)، ومتابعة كافة الإجراءات أمام مصلحة الجوازات والهجرة والجنسية، وحل أي إشكاليات تتعلق بتأشيرات الدخول أو تجاوز المدة القانونية للإقامة.',
    details_en: 'We assist foreign residents in Egypt with obtaining and renewing residency permits of all types (work, study, marriage to an Egyptian, investment), handling all procedures before the Passports, Immigration & Nationality Authority, and resolving issues related to entry visas or overstaying the legal residency period.',
    sort_order: 2,
  },
  {
    id: 1,
    slug: 'civil-law',
    icon: 'file',
    title_ar: 'القانون المدني',
    title_en: 'Civil Law',
    summary_ar: 'التعويضات، منازعات العقود، الملكية والحيازة، والتنفيذ.',
    summary_en: 'Compensation, contract disputes, ownership & possession, enforcement.',
    details_ar: 'نمثّل عملاءنا في دعاوى التعويض والمسؤولية المدنية، ومنازعات العقود والتنفيذ، وقضايا الملكية والحيازة أمام المحاكم الابتدائية والاستئناف ومحكمة النقض، مع صياغة المذكرات والطعون بأعلى درجات الدقة.',
    details_en: 'We represent clients in compensation and civil liability claims, contract and enforcement disputes, and ownership and possession cases before Courts of First Instance, Appeal and Cassation — drafting memoranda and appeals with the highest precision.',
    sort_order: 3,
  },
  {
    id: 2,
    slug: 'commercial-corporate',
    icon: 'building',
    title_ar: 'القانون التجاري والشركات',
    title_en: 'Commercial & Corporate',
    summary_ar: 'تأسيس الشركات، العقود التجارية، الحوكمة، ومنازعات الأعمال.',
    summary_en: 'Company formation, commercial contracts, governance & business disputes.',
    details_ar: 'نقدم خدمات تأسيس الشركات بكافة أنواعها، وصياغة عقود الشراكة والتوزيع والوكالات التجارية، والتمثيل في المنازعات التجارية والإفلاس، وحوكمة مجالس الإدارة بما يتوافق مع قانون الشركات المصري.',
    details_en: 'Company formation of all types, drafting partnership, distribution and agency agreements, representation in commercial and bankruptcy disputes, and board governance in line with Egyptian corporate law.',
    sort_order: 4,
  },
  {
    id: 3,
    slug: 'arbitration',
    icon: 'handshake',
    title_ar: 'التحكيم وتسوية المنازعات',
    title_en: 'Arbitration & Disputes',
    summary_ar: 'التحكيم المحلي والدولي، وتنفيذ أحكام المحكمين.',
    summary_en: 'Local & international arbitration and enforcement of awards.',
    details_ar: 'تمثيل متخصص أمام مراكز التحكيم المحلية والدولية، وصياغة شروط التحكيم في العقود، وتنفيذ أحكام المحكمين، مع خبرة في منازعات المقاولات والاستثمار والتجارة الدولية.',
    details_en: 'Specialised representation before local and international arbitration centres, drafting arbitration clauses, enforcement of arbitral awards, with experience in construction, investment and international trade disputes.',
    sort_order: 5,
  },
  {
    id: 4,
    slug: 'family-law',
    icon: 'users',
    title_ar: 'الأحوال الشخصية',
    title_en: 'Family & Personal Status',
    summary_ar: 'الحضانة والنفقات والميراث والوصايا بسرّية تامة.',
    summary_en: 'Custody, maintenance, inheritance & wills in strict confidence.',
    details_ar: 'نتولى قضايا الزواج والطلاق والحضانة والنفقات والميراث والوصايا بسرّية تامة وحساسية إنسانية، مع السعي الدائم للحلول الودية التي تحفظ كرامة الأسرة قبل اللجوء إلى التقاضي.',
    details_en: 'We handle marriage, divorce, custody, maintenance, inheritance and wills with absolute discretion and human sensitivity — always seeking amicable solutions that preserve family dignity before resorting to litigation.',
    sort_order: 6,
  },
  {
    id: 5,
    slug: 'criminal-law',
    icon: 'gavel',
    title_ar: 'القانون الجنائي',
    title_en: 'Criminal Law',
    summary_ar: 'الدفاع الجنائي أمام النيابة والمحاكم الجنائية والاقتصادية.',
    summary_en: 'Criminal defence before prosecution and criminal courts.',
    details_ar: 'دفاع متخصص في الجنايات والجنح أمام النيابة العامة ومحاكم الجنايات والجنح والمحاكم الاقتصادية، بما يشمل قضايا الأموال العامة والجرائم الإلكترونية، مع حضور التحقيقات وصياغة الدفوع الجوهرية.',
    details_en: 'Specialised defence in felonies and misdemeanours before the Public Prosecution, criminal and economic courts — including public funds and cybercrime cases — with attendance at interrogations and substantive defences.',
    sort_order: 7,
  },
  {
    id: 6,
    slug: 'real-estate',
    icon: 'landmark',
    title_ar: 'العقارات والإيجارات',
    title_en: 'Real Estate & Tenancy',
    summary_ar: 'التسجيل العقاري، عقود التطوير، وتسوية المنازعات العقارية.',
    summary_en: 'Registration, development contracts & property dispute resolution.',
    details_ar: 'فحص الملكية والتسجيل بالشهر العقاري، وصياغة عقود البيع والتطوير العقاري، وتسوية المنازعات العقارية، ومراجعة التراخيص — لحماية استثمارك العقاري من أي مفاجآت قانونية.',
    details_en: 'Title examination and registration, drafting sale and development agreements, settling real estate disputes and reviewing licences — protecting your property investment from any legal surprises.',
    sort_order: 8,
  },
  {
    id: 7,
    slug: 'labour-law',
    icon: 'briefcase',
    title_ar: 'قانون العمل',
    title_en: 'Labour & Employment',
    summary_ar: 'عقود العمل، منازعات الفصل، والمستحقات العمالية.',
    summary_en: 'Employment contracts, dismissal disputes & entitlements.',
    details_ar: 'صياغة عقود العمل واللوائح الداخلية، والتمثيل في منازعات الفصل التعسفي والمستحقات العمالية، وتقديم الاستشارات المستمرة لإدارات الموارد البشرية بما يتوافق مع قانون العمل المصري.',
    details_en: 'Drafting employment contracts and internal regulations, representation in unfair dismissal and entitlements disputes, and ongoing counsel to HR departments in line with Egyptian labour law.',
    sort_order: 9,
  },
  {
    id: 8,
    slug: 'administrative-law',
    icon: 'scale',
    title_ar: 'القضاء الإداري ومجلس الدولة',
    title_en: 'Administrative & State Council',
    summary_ar: 'الطعن على القرارات الإدارية ومنازعات مجلس الدولة.',
    summary_en: 'Challenging decisions & State Council litigation.',
    details_ar: 'الطعن على القرارات الإدارية أمام محاكم مجلس الدولة، وقضايا التعويض عن أخطاء الإدارة، ومنازعات العقود الإدارية والمناقصات، والدفاع عن حقوق الموظفين العموميين.',
    details_en: "Challenging administrative decisions before State Council courts, compensation claims against administrative faults, public contract and tender disputes, and defending public employees' rights.",
    sort_order: 10,
  },
];

export const localInsights: Insight[] = [
  {
    id: 1,
    slug: 'commercial-contract-essentials',
    category_ar: 'القانون التجاري',
    category_en: 'Commercial Law',
    title_ar: 'قبل أن توقّع: العناصر الجوهرية للعقد التجاري المحكم',
    title_en: 'Before You Sign: The Essentials of a Sound Commercial Contract',
    excerpt_ar: 'خمسة بنود جوهرية يجب أن يتضمنها أي عقد تجاري قبل التوقيع — من واقع خبرتنا العملية.',
    excerpt_en: 'Five essential clauses every commercial contract must include before signing — from our practical experience.',
    body_ar: 'الكثير من المنازعات التجارية كان يمكن تجنّبها لو أُحسنت صياغة العقد منذ البداية. فالعقد المحكم ليس مجرد ورقة، بل هو دستور العلاقة بين الطرفين: يحدد الالتزامات بدقة، ويرسم آلية فضّ النزاع، ويحمي الحقوق قبل أن تُهدد.\n\nمن واقع خبرتنا، نوصي بأن يتضمن أي عقد تجاري خمسة عناصر جوهرية: تحديدًا دقيقًا لمحل العقد ونطاقه، وجدولًا واضحًا للالتزامات المالية والمواعيد، وشرطًا للجزاءات والتعويضات، وآلية مكتوبة لحل النزاعات (تفاوض ثم تحكيم أو قضاء)، وأخيرًا بندًا للسرّية وحماية البيانات.\n\nتذكّر أن تكلفة مراجعة العقد قبل التوقيع لا تُقارن أبدًا بتكلفة النزاع بعده. استشارة قانونية واحدة قد توفر عليك سنوات من التقاضي.',
    body_en: 'Many commercial disputes could have been avoided with a well-drafted contract from the outset. A sound contract is not mere paper — it is the constitution of the relationship: it defines obligations precisely, maps dispute resolution, and protects rights before they are threatened.\n\nFrom our experience, we recommend every commercial contract include five essentials: a precise definition of scope, a clear schedule of financial obligations and deadlines, a penalties and compensation clause, a written dispute-resolution mechanism (negotiation, then arbitration or courts), and finally a confidentiality and data-protection clause.\n\nRemember: the cost of reviewing a contract before signing is never comparable to the cost of disputing it afterwards. A single legal consultation may save you years of litigation.',
    image: '/images/conference.jpg',
    published_at: '2026-09-10T10:00:00+00:00',
    read_minutes: 5,
  },
  {
    id: 2,
    slug: 'real-estate-due-diligence',
    category_ar: 'العقارات',
    category_en: 'Real Estate',
    title_ar: 'الدليل العملي لفحص العقار قبل الشراء في مصر',
    title_en: 'A Practical Guide to Property Due Diligence in Egypt',
    excerpt_ar: 'خطوات عملية لفحص الملكية وتأمين صفقة الشراء قبل دفع أي مبلغ.',
    excerpt_en: 'Practical steps to examine title and secure your purchase before paying anything.',
    body_ar: 'شراء عقار هو غالبًا أكبر قرار مالي في حياة الإنسان، ومع ذلك يتسرع الكثيرون في إتمامه دون فحص قانوني كافٍ. الخطوة الأولى والأهم هي التحقق من سند الملكية وتسلسله، والتأكد من خلوّ العقار من الرهون والحجوزات والنزاعات القضائية.\n\nبعد ذلك تأتي مراجعة التراخيص والمخالفات، ومطابقة العقار على الطبيعة مع المستندات، ثم صياغة عقد البيع بما يضمن حقوق المشتري — بما في ذلك شروط التسليم والضمانات وآلية سداد الثمن عبر وسائل موثقة.\n\nنصيحتنا الدائمة: لا تدفع أي مبلغ — ولو عربونًا — قبل مراجعة محامٍ متخصص. فحص الملكية يستغرق أيامًا، لكن إصلاح الخطأ قد يستغرق سنوات.',
    body_en: 'Buying property is often the biggest financial decision of a lifetime, yet many rush through it without sufficient legal examination. The first and most important step is verifying the title deed and its chain, and confirming the property is free of mortgages, seizures and court disputes.\n\nNext comes reviewing licences and violations, matching the property on the ground with the documents, then drafting the sale contract to protect the buyer — including delivery terms, warranties and a documented payment mechanism.\n\nOur standing advice: never pay any sum — not even a deposit — before consulting a specialised lawyer. A title check takes days; fixing a mistake can take years.',
    image: '/images/architecture.jpg',
    published_at: '2026-08-22T10:00:00+00:00',
    read_minutes: 6,
  },
  {
    id: 3,
    slug: 'arbitration-clause-guide',
    category_ar: 'التحكيم',
    category_en: 'Arbitration',
    title_ar: 'التحكيم التجاري: كيف تصوغ شرطًا يحميك فعلًا؟',
    title_en: 'Commercial Arbitration: Drafting a Clause That Truly Protects You',
    excerpt_ar: 'لماذا يبدأ نجاح التحكيم من صياغة شرطه في العقد؟ وما عناصر الشرط الجيد؟',
    excerpt_en: 'Why does arbitration succeed or fail at the drafting of its clause? The anatomy of a good clause.',
    body_ar: 'يلجأ الكثيرون إلى التحكيم هربًا من بطء التقاضي، لكن قليلين يدركون أن نجاح التحكيم يبدأ من صياغة شرط التحكيم نفسه في العقد. شرطٌ غامض أو ناقص قد يؤدي إلى نزاع حول التحكيم قبل النزاع الأصلي.\n\nالشرط الجيد يحدد بوضوح: نطاق المنازعات الخاضعة للتحكيم، وعدد المحكمين وآلية تعيينهم، ومكان التحكيم ولغته، والقانون الواجب التطبيق، ومركز التحكيم المتفق عليه إن وُجد.\n\nفي مكتبنا نمثّل العملاء أمام مراكز التحكيم المحلية والدولية، ونصوغ شروط التحكيم بما يضمن سرعة الفصل وحجّية الحكم وقابليته للتنفيذ.',
    body_en: 'Many turn to arbitration to escape slow litigation, yet few realise that successful arbitration begins with the arbitration clause itself. A vague or incomplete clause can trigger a dispute about arbitration before the original dispute.\n\nA good clause clearly defines: the scope of disputes subject to arbitration, the number of arbitrators and appointment mechanism, the seat and language, the applicable law, and the agreed arbitral institution if any.\n\nOur firm represents clients before local and international arbitral centres, and drafts arbitration clauses that ensure speedy resolution and enforceable awards.',
    image: '/images/marble.jpg',
    published_at: '2026-07-15T10:00:00+00:00',
    read_minutes: 4,
  },
  {
    id: 4,
    slug: 'unfair-dismissal-rights',
    category_ar: 'قانون العمل',
    category_en: 'Labour Law',
    title_ar: 'الفصل التعسفي: حقوق العامل وخطوات المطالبة بها',
    title_en: 'Unfair Dismissal: Workers’ Rights and How to Claim Them',
    excerpt_ar: 'حقوقك عند الفصل التعسفي: الخطوات العملية من التوثيق حتى المحكمة العمالية.',
    excerpt_en: 'Your rights in unfair dismissal: practical steps from documentation to the labour court.',
    body_ar: 'الفصل التعسفي من أكثر المنازعات العمالية شيوعًا، والقانون المصري يوفر للعامل حماية حقيقية متى أُحسن استخدامها. الأصل أنه لا يجوز فصل العامل إلا بحكم قضائي أو بقرار من اللجنة المختصة في الحالات التي حددها القانون حصرًا.\n\nإذا تعرضت للفصل، فاحرص على: توثيق واقعة المنع من العمل فورًا، والاحتفاظ بصورة من عقد العمل وكشوف المرتبات، والتقدم بشكوى لمكتب العمل خلال المواعيد القانونية، ثم اللجوء إلى المحكمة العمالية للمطالبة بالتعويض أو العودة للعمل.\n\nأما أصحاب الأعمال، فننصحهم دائمًا بتوثيق المخالفات وإتباع الإجراءات القانونية قبل أي قرار — فالوقاية هنا أرخص بكثير من التعويضات.',
    body_en: 'Unfair dismissal is among the most common labour disputes, and Egyptian law offers workers genuine protection when properly invoked. The rule is that a worker may not be dismissed except by court judgment or competent committee decision in the cases exhaustively defined by law.\n\nIf dismissed, be sure to: document the denial of work immediately, keep copies of your contract and pay slips, file a complaint with the labour office within statutory deadlines, then resort to the labour court to claim compensation or reinstatement.\n\nFor employers, we always advise documenting violations and following legal procedures before any decision — prevention here is far cheaper than compensation.',
    image: '/images/signing.jpg',
    published_at: '2026-06-05T10:00:00+00:00',
    read_minutes: 5,
  },
  {
    id: 5,
    slug: 'challenging-administrative-decisions',
    category_ar: 'القضاء الإداري',
    category_en: 'Administrative Law',
    title_ar: 'الطعن على القرارات الإدارية: المواعيد والأسباب',
    title_en: 'Challenging Administrative Decisions: Deadlines & Grounds',
    excerpt_ar: 'ستون يومًا قد تصنع الفارق: كيف تطعن على القرار الإداري أمام مجلس الدولة؟',
    excerpt_en: 'Sixty days can make the difference: how to challenge administrative decisions before the State Council.',
    body_ar: 'قرار إداري واحد — برفض ترخيص أو إنهاء تعاقد أو جزاء تأديبي — قد يقلب حياة الإنسان أو مسار الشركة. والقضاء الإداري المصري، ممثلًا في مجلس الدولة، هو الحارس الأمين لمبدأ المشروعية وحقوق الأفراد في مواجهة الإدارة.\n\nالطعن على القرار الإداري يخضع لمواعيد صارمة (ستون يومًا من العلم بالقرار)، ويتطلب صياغة دقيقة لأوجه البطلان: عيب الاختصاص، أو عيب الشكل، أو مخالفة القانون، أو إساءة استعمال السلطة، أو عيب السبب.\n\nلا تنتظر حتى يتحصن القرار بفوات الميعاد. استشارة مبكرة قد تكون الفارق بين إلغاء القرار وتعويضك، وبين تحصنه نهائيًا.',
    body_en: 'A single administrative decision — denying a licence, terminating a contract, imposing discipline — can upend a life or a company. Egypt’s administrative judiciary, embodied in the State Council, stands as the faithful guardian of legality and individual rights against the administration.\n\nChallenging an administrative decision is subject to strict deadlines (sixty days from knowledge of the decision) and requires precise pleading of annulment grounds: lack of competence, formal defect, violation of law, abuse of power, or flawed reasoning.\n\nDo not wait until the decision becomes immune by lapse of time. An early consultation may be the difference between annulment with compensation — and final immunity.',
    image: '/images/towers.jpg',
    published_at: '2026-04-18T10:00:00+00:00',
    read_minutes: 6,
  },
  {
    id: 6,
    slug: 'inheritance-fair-division',
    category_ar: 'الأحوال الشخصية',
    category_en: 'Family Law',
    title_ar: 'الميراث: بين عدالة القسمة وحفظ صلة الرحم',
    title_en: 'Inheritance: Between Just Division and Preserving Kinship',
    excerpt_ar: 'من حصر التركة إلى القسمة الرضائية: كيف تحسم الميراث بعدل وتحفظ صلة الرحم؟',
    excerpt_en: 'From inventory to amicable division: settling inheritance justly while preserving kinship.',
    body_ar: 'الميراث من أكثر القضايا حساسية، إذ تمس صلة الرحم قبل أن تمس المال. ومع ذلك، فإن وضوح القواعد الشرعية والقانونية يجعل معظم منازعاته قابلة للحسم العادل متى أُحسنت الإدارة.\n\nننصح الورثة بالبدء بحصر التركة حصرًا دقيقًا وموثقًا، ثم محاولة القسمة الرضائية بعقود موثقة تحفظ حقوق الجميع — خاصة القصّر — قبل اللجوء إلى دعوى الفرز والتجنيب التي قد تطول.\n\nكما نوصي كل مالك بأن يوثّق وصيته ويحدد ممتلكاته بوضوح في حياته، رحمةً بورثته وحفظًا لصلتهم بعد رحيله. فأجمل ما يتركه الإنسان خلفه: مالٌ مُقسّم بعدل، وأهلٌ متّحدون.',
    body_en: 'Inheritance is among the most sensitive matters, touching kinship before money. Yet the clarity of Sharia and legal rules makes most of its disputes fairly resolvable with proper handling.\n\nWe advise heirs to begin with a precise, documented inventory of the estate, then attempt an amicable division through notarised agreements protecting everyone — especially minors — before resorting to partition lawsuits that may drag on.\n\nWe also urge every owner to document their will and clearly identify their assets during their lifetime — a mercy to their heirs and a preservation of kinship after they pass. The finest legacy: wealth divided justly, and a family united.',
    image: '/images/library.jpg',
    published_at: '2026-03-02T10:00:00+00:00',
    read_minutes: 5,
  },
];
